<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->truncate();

        DB::table('san_phams')->insert([
            ['id' => '1', 'tieu_de' => 'iPhone 13 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-13_2_.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '13690000', 'gia_khuyen_mai' => '18990000', 'mo_ta' => 'iPhone 13 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '2', 'tieu_de' => 'iPhone 15 Pro Max 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_3.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '29.290.000', 'gia_khuyen_mai' => '34.990.000', 'mo_ta' => 'iPhone 15 Pro Max 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '3', 'tieu_de' => 'iPhone 15 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1__1.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '19.190.000', 'gia_khuyen_mai' => '22.990.000', 'mo_ta' => 'iPhone 15 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '4', 'tieu_de' => 'iPhone 14 Pro Max 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14-pro_2__5.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '26.690.000', 'gia_khuyen_mai' => '29.990.000', 'mo_ta' => 'iPhone 14 Pro Max 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '5', 'tieu_de' => 'iPhone 15 Pro 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_4.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '23.990.000', 'gia_khuyen_mai' => '28.990.000', 'mo_ta' => 'iPhone 15 Pro 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '6', 'tieu_de' => 'iPhone 15 Plus 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1_.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '22.250.000', 'gia_khuyen_mai' => '25.990.000', 'mo_ta' => 'iPhone 15 Plus 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '7', 'tieu_de' => 'iPhone 11 64GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-11.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '8.690.000', 'gia_khuyen_mai' => '11.990.000', 'mo_ta' => 'iPhone 11 64GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '8', 'tieu_de' => 'iPhone 14 128GB  | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14_1.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '16.450.000', 'gia_khuyen_mai' => '22.990.000', 'mo_ta' => 'iPhone 14 128GB  | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '9', 'tieu_de' => 'iPhone 14 Pro 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14-pro_2__4.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '23.690.000', 'gia_khuyen_mai' => '27.990.000', 'mo_ta' => 'iPhone 14 Pro 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '10', 'tieu_de' => 'iPhone 14 Pro Max 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14-pro-max-256gb.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '27.290.000', 'gia_khuyen_mai' => '32.990.000', 'mo_ta' => 'iPhone 14 Pro Max 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '11', 'tieu_de' => 'iPhone 14 Plus 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14-plus_1_.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '19.350.000', 'gia_khuyen_mai' => '24.990.000', 'mo_ta' => 'iPhone 14 Plus 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '12', 'tieu_de' => 'iPhone 15 Plus 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus-256gb_2.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '24.450.000', 'gia_khuyen_mai' => '28.990.000', 'mo_ta' => 'iPhone 15 Plus 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '13', 'tieu_de' => 'iPhone 15 Pro 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-256gb.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '27.590.000', 'gia_khuyen_mai' => '31.990.000', 'mo_ta' => 'iPhone 15 Pro 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '14', 'tieu_de' => 'iPhone 11 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-11-128gb.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '9.890.000', 'gia_khuyen_mai' => '13.990.000', 'mo_ta' => 'iPhone 11 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '15', 'tieu_de' => 'iPhone 15 Pro Max 512GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_5.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '35.490.000', 'gia_khuyen_mai' => '40.990.000', 'mo_ta' => 'iPhone 15 Pro Max 512GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '16', 'tieu_de' => 'iPhone 15 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus-256gb_3.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '22.590.000', 'gia_khuyen_mai' => '25.990.000', 'mo_ta' => 'iPhone 15 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '17', 'tieu_de' => 'iPhone 13 256GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/1/1/11_3_12_2_1_6.jpg', 'slug_san_pham' => 'iphone',  'gia_ban' => '17.490.000', 'gia_khuyen_mai' => '21.990.000', 'mo_ta' => 'iPhone 13 256GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '18', 'tieu_de' => 'iPhone 12 64GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-12.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '11.790.000', 'gia_khuyen_mai' => '15.990.000', 'mo_ta' => 'iPhone 12 64GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '19', 'tieu_de' => 'iPhone 15 Pro Max 1TB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-256gb_1.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '42.890.000', 'gia_khuyen_mai' => '46.990.000', 'mo_ta' => 'iPhone 15 Pro Max 1TB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '20', 'tieu_de' => 'iPhone 13 Pro Max 128GB | Chính hãng VN/A', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-13-pro-max.png', 'slug_san_pham' => 'iphone',  'gia_ban' => '22.990.000', 'gia_khuyen_mai' => '28.990.000', 'mo_ta' => 'iPhone 13 Pro Max 128GB | Chính hãng VN/A', 'id_dai_ly' => '1', 'id_danh_muc' => '1'],
            ['id' => '21', 'tieu_de' => 'OPPO Reno11 F 5G 8GB 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-oppo-reno-11-f-2.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '8.290.000', 'gia_khuyen_mai' => '8.990.000', 'mo_ta' => 'OPPO Reno11 F 5G 8GB 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '22', 'tieu_de' => 'OPPO Find X5 Pro 12GB 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/o/download_1__6_6.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '16.790.000', 'gia_khuyen_mai' => '19.990.000', 'mo_ta' => 'OPPO Find X5 Pro 12GB 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '23', 'tieu_de' => 'OPPO Reno10 5G 8GB 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/r/e/reno10_5g_-_combo_product_-_blue.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '8.990.000', 'gia_khuyen_mai' => '10.990.000', 'mo_ta' => 'OPPO Reno10 5G 8GB 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '24', 'tieu_de' => 'OPPO A77s 8GB 128GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a55_1_.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '5.190.000', 'gia_khuyen_mai' => '6.290.000', 'mo_ta' => 'OPPO A77s 8GB 128GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '25', 'tieu_de' => 'OPPO A18 4GB 128GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a18.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '3.690.000', 'gia_khuyen_mai' => '3.990.000', 'mo_ta' => 'OPPO A18 4GB 128GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '26', 'tieu_de' => 'OPPO A58 4G 6GB 128GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a58_1_1.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '4.490.000', 'gia_khuyen_mai' => '4.990.000', 'mo_ta' => 'OPPO A58 4G 6GB 128GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '27', 'tieu_de' => 'OPPO Reno7 5G (8GB 256GB)', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno-7_1.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '7.590.000', 'gia_khuyen_mai' => '12.990.000', 'mo_ta' => 'OPPO Reno7 5G (8GB 256GB)', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '28', 'tieu_de' => 'OPPO A78 4G (8GB 256GB)', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a78.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '6.990.000', 'gia_khuyen_mai' => '12.990.000', 'mo_ta' => 'OPPO A78 4G (8GB 256GB)', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '29', 'tieu_de' => 'OPPO Find N3 16GB 512GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/f/i/find_n3_-_combo_product_-_gold.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '41.990.000', 'gia_khuyen_mai' => '44.990.000', 'mo_ta' => 'OPPO Find N3 16GB 512GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '30', 'tieu_de' => 'OPPO Reno10 128GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno10._1.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '7.890.000', 'gia_khuyen_mai' => '9.990.000', 'mo_ta' => 'OPPO Reno10 128GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '31', 'tieu_de' => 'OPPO A17K', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a17k.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '2.790.000', 'gia_khuyen_mai' => '3.290.000', 'mo_ta' => 'OPPO A17K', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '32', 'tieu_de' => 'OPPO Find N3 Flip 12GB 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/f/i/find-n3-flip-vang_1.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '22.990.000', 'gia_khuyen_mai' => '3.290.000', 'mo_ta' => 'OPPO Find N3 Flip 12GB 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '33', 'tieu_de' => 'OPPO Reno 7 Pro', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno7-pro_1.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '9.990.000', 'gia_khuyen_mai' => '18.990.000', 'mo_ta' => 'OPPO Reno 7 Pro', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '34', 'tieu_de' => 'OPPO Find N2 Flip 8Gb 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-find-n2-flip.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '16.990.000', 'gia_khuyen_mai' => '19.990.000', 'mo_ta' => 'OPPO Find N2 Flip 8Gb 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '35', 'tieu_de' => 'OPPO Reno8 T 4G 256GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno-8t-4g-256gb.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '7.190.000', 'gia_khuyen_mai' => '8.490.000', 'mo_ta' => 'OPPO Reno8 T 4G 256GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '36', 'tieu_de' => 'OPPO Reno8 T 5G (8GB - 128GB)', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-reno-8t.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '7.890.000', 'gia_khuyen_mai' => '9.990.000', 'mo_ta' => 'OPPO Reno8 T 5G (8GB - 128GB)', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '37', 'tieu_de' => 'OPPO A15', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a15_1_.jpg', 'slug_danh_muc' => 'oppo', 'gia_ban' => '3.290.000', 'gia_khuyen_mai' => '3.690.000', 'mo_ta' => 'OPPO A15', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '38', 'tieu_de' => 'OPPO A16', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/c/o/combo_-_a16_-_b_c.jpg', 'slug_danh_muc' => 'oppo', 'gia_ban' => '2.790.000', 'gia_khuyen_mai' => '3.990.000', 'mo_ta' => 'OPPO A16', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
            ['id' => '39', 'tieu_de' => 'OPPO A57 4GB 128GB', 'thumbnail' => 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-a57.png', 'slug_danh_muc' => 'oppo', 'gia_ban' => '3.790.000', 'gia_khuyen_mai' => '4.990.000', 'mo_ta' => 'OPPO A57 4GB 128GB', 'id_dai_ly' => '3',  'id_danh_muc' => '1'],
        ]);
    }
}
